- platform: wake_on_lan
  mac: !secret mediabox_mac
  name: mediabox_wol
  host: !secret mediabox_ip

- platform: template
  switches:
    mediabox:
      value_template: '{{ states.switch.mediabox_wol.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.mediabox_wol
      turn_off:
        service: shell_command.mediabox_off
