homeassistant:
  name: !secret name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret api_password
  server_host: !secret server_host
  server_port: !secret server_port
  base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

logger:
  default: info
  logs:
    homeassistant.core: warn
    homeassistant.components.envisalink: warn

# Discover some devices automatically
discovery:
  ignore:
    - yamaha
    - apple_tv
    - harmony

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time
history:

recorder:
  db_url: !secret db_url
  purge_keep_days: 14
  purge_interval: 1
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - camera
      - group
      - media_player
    entities:
      - sensor.last_boot
      - sensor.date
      - sensor.date__time
      - sensor.pws_weather_1d
      - sensor.pws_weather_1d_2
      - sensor.pws_weather_2d
      - sensor.pws_weather_2d_2
      - sensor.pws_temp_f_2
      - sensor.pws_temp_f
      - sensor.pws_alerts
      - sensor.home_alarm_keypad
      - sun.sun
      - cover.myq

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
# tts:
#   - platform: google

notify: !include notifier.yaml
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
switch: !include_dir_merge_list switches/
cover: !include_dir_merge_list covers/
group: !include_dir_merge_named groups/

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  sensors:
    monitored_conditions:
      - 'humidity'
      - 'temperature'
      - 'operation_mode'
      - 'target'
      - 'hvac_state'
  binary_sensors:
    monitored_conditions:

ring:
  username: !secret ring_username
  password: !secret ring_password


device_tracker:
  - platform: unifi
    username: !secret unifi_username
    password: !secret unifi_password
    host: !secret unifi_host
    new_device_defaults:
      track_new_devices: False

input_select:
  occupants:
    name: Occupancy
    icon: mdi:account
    initial: auto
    options:
      - auto
      - dogs
      - guests
  climate_mode:
    # not used yet
    name: Climate Mode
    options:
      - eco
      - cool
      - heat

input_number:
  climate_temp:
    # not used yet
    name: Climate Temp
    initial: 72
    min: 55
    max: 85
    step: 1
    mode: slider

# input_boolean:
#   front_door:
#     name: Front door
#     initial: off
#     icon: mdi:door

envisalink: !include envisalink.yaml

lutron: !include lutron.yaml
