homeassistant:
  name: !secret name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  customize: !include customize.yaml
  internal_url: !secret internal_url
  unit_system: us_customary
  country: US
  time_zone: America/Los_Angeles
  currency: USD
# Dashboards
lovelace:
  dashboards:
    lovelace:
      mode: yaml
      filename: dashboards/main.yaml
      title: Overview
      icon: mdi:view-dashboard
      show_in_sidebar: true
    debug-dashboard:
      mode: yaml
      filename: dashboards/debug.yaml
      title: Debug
      icon: mdi:information-variant-box-outline
      show_in_sidebar: true
  resources:
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
logger:
  default: info
  logs:
    homeassistant.core: warn
    homeassistant.components.ambient_station: warn
    engineio.client: warn
    custom_components.doorking_1812ap: debug
# list most groups to track groups.people to see if it transitions
# to unknown when there's a network hiccup
recorder:
  db_url: !secret db_url
  purge_keep_days: 3650
  exclude:
    domains:
      - weblink
      - updater
      - camera
      - media_player
      - weather
    entities:
      - sensor.last_boot
      - sensor.date
      - sensor.date_time
      - sensor.home_alarm_keypad
      - sensor.alarm_status_with_zone_name
      - sun.sun
      - group.alarm
      - group.alarm_sensors
      - group.climate
      - group.climate_other
      - group.general
      - group.lights
      - group.nest
      - group.ring
      - group.shades
      - group.solar
      - group.switches
      - group.zwave
notify: !include notifier.yaml
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
switch: !include_dir_merge_list switches/
cover: !include_dir_merge_list covers/
group: !include_dir_merge_named groups/
shell_command: !include_dir_merge_named shell_commands/
template: !include_dir_merge_list templates
emulated_hue:
  listen_port: 28888
input_select:
  occupants:
    name: Occupancy
    icon: mdi:account
    options:
      - auto
      - dogs
      - guests
  climate_mode:
    name: Climate Mode
    options:
      - "off"
      - cool
      - heat
      - "fan only"
input_number:
  climate_temp:
    name: Temp
    min: 50
    max: 85
    step: 1
    mode: box
input_boolean:
  master_floor_heat:
    icon: mdi:radiator
  guest_floor_heat:
    icon: mdi:radiator
  kids_floor_heat:
    icon: mdi:radiator
wake_on_lan:
weather:
wemo:
  discovery: true
zone:
  - name: home
    latitude: !secret latitude
    longitude: !secret longitude
energy:
