homeassistant:
  name: !secret name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Put Lovelace in yaml mode
lovelace:
  mode: yaml

# Enables configuration UI
config:

http:
  api_password: !secret api_password
  server_host: !secret server_host
  server_port: !secret server_port
  base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

logger:
  default: info
  logs:
    homeassistant.core: warn
    homeassistant.components.envisalink: info
    pyenvisalink.envisalink_base_client: info
    homeassistant.components.tesla: debug
    homeassistant.components.sensor.tesla: debug
    homeassistant.components.binary_sensor.tesla: debug


# Discover some devices automatically
discovery:
  ignore:
    - yamaha
    - apple_tv

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time
history:

recorder:
  db_url: !secret db_url
  purge_keep_days: 14
  purge_interval: 1
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - camera
      - group
      - media_player
      - weather
    entities:
      - sensor.last_boot
      - sensor.date
      - sensor.date_time
      - sensor.home_alarm_keypad
      - sun.sun
      - sensor.schlage_be469_touchscreen_deadbolt_access_control_1
      - sensor.schlage_be469_touchscreen_deadbolt_alarm_level_1
      - sensor.schlage_be469_touchscreen_deadbolt_alarm_type_1
      - sensor.schlage_be469_touchscreen_deadbolt_burglar_1
      - sensor.schlage_be469_touchscreen_deadbolt_power_management_1
      - sensor.schlage_be469_touchscreen_deadbolt_sourcenodeid_1
      - sensor.schlage_be469_touchscreen_deadbolt_system_1
      - sensor.schlage_be469_touchscreen_deadbolt_access_control_2
      - sensor.schlage_be469_touchscreen_deadbolt_alarm_level_2
      - sensor.schlage_be469_touchscreen_deadbolt_alarm_type_2
      - sensor.schlage_be469_touchscreen_deadbolt_burglar_2
      - sensor.schlage_be469_touchscreen_deadbolt_power_management_2
      - sensor.schlage_be469_touchscreen_deadbolt_sourcenodeid_2
      - sensor.schlage_be469_touchscreen_deadbolt_system_2
      - sensor.schlage_be469_touchscreen_deadbolt_access_control_3
      - sensor.schlage_be469_touchscreen_deadbolt_alarm_level_3
      - sensor.schlage_be469_touchscreen_deadbolt_alarm_type_3
      - sensor.schlage_be469_touchscreen_deadbolt_burglar_3
      - sensor.schlage_be469_touchscreen_deadbolt_power_management_3
      - sensor.schlage_be469_touchscreen_deadbolt_sourcenodeid_3
      - sensor.schlage_be469_touchscreen_deadbolt_system_3
      - sensor.ring_front_door_last_activity
      - cover.myq

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
# tts:
#   - platform: google

notify: !include notifier.yaml
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
switch: !include_dir_merge_list switches/
cover: !include_dir_merge_list covers/
group: !include_dir_merge_named groups/


device_tracker:
  - platform: unifi
    username: !secret unifi_username
    password: !secret unifi_password
    host: !secret unifi_host
    new_device_defaults:
      track_new_devices: False

envisalink: !include envisalink.yaml

input_select:
  occupants:
    name: Occupancy
    icon: mdi:account
    options:
      - auto
      - dogs
      - guests
  climate_mode:
    name: Climate Mode
    options:
      - eco
      - cool
      - heat

input_number:
  climate_temp:
    name: Climate Temp
    min: 55
    max: 85
    step: 1
    mode: slider

input_boolean:
  master_floor_heat:
    icon: mdi:radiator
  guest_floor_heat:
    icon: mdi:radiator

ios: !include ios.yaml

lutron: !include lutron.yaml

neato:
  username: !secret neato_username
  password: !secret neato_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  sensors:
    monitored_conditions:
      - 'humidity'
      - 'temperature'
      - 'operation_mode'
      - 'target'
      - 'hvac_state'
  binary_sensors:
    monitored_conditions:

nuheat:
  username: !secret nuheat_username
  password: !secret nuheat_password
  devices: !secret nuheat_devices

ring:
  username: !secret ring_username
  password: !secret ring_password

# tesla:
#   username: !secret tesla_username
#   password: !secret tesla_password
#   scan_interval: 86400

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
