title: Westridge Debug

excluded_entities:
views:
  - title: Sensors
    id: sensors
    cards:
      - type: entities
        title: Climate Other
        show_header_toggle: false
        entities:
          - switch.great_room_fan
          - climate.master_nuheat
          - climate.kids_nuheat
          - climate.guest_nuheat
      - type: entities
        entities:
          - binary_sensor.elara_bedroom
          - binary_sensor.front_door
          - binary_sensor.front_windows
          - binary_sensor.guest_bedroom
          - binary_sensor.hall_bath
          - binary_sensor.kep_bedroom
          - binary_sensor.kitchen
          - binary_sensor.laundry
          - binary_sensor.lift_slide
          - binary_sensor.master
          - binary_sensor.master_bath
          - binary_sensor.mudroom_powder
          - binary_sensor.pantry
          - binary_sensor.fire_sprinklers
          - entity: binary_sensor.home_alarm_ready
            name: Ready
          - entity: sensor.home_alarm_keypad
            name: Keypad
          - entity: binary_sensor.home_alarm_alarm
            name: Alarm
          - entity: binary_sensor.home_alarm_fire
            name: Fire
        title: Home Alarm

      - type: entities
        entities:
          - switch.tasmota_3
          - switch.tasmota_4

      - type: custom:auto-entities
        card:
          type: entities
          title: Weather Station
        filter:
          include:
            - entity_id: "sensor.westridge*"
        sort:
          method: name
      - type: custom:auto-entities
        card:
          type: entities
          title: Weather Station (local)
        filter:
          include:
            - entity_id: "sensor.weather_local_*"
        sort:
          method: name
      - type: custom:auto-entities
        card:
          type: entities
          title: Tasmota
        filter:
          include:
            - entity_id: "sensor.tasmota.*"
        sort:
          method: name
      # - type: grid
      #   square: false
      #   columns: 1
      #   cards:
      #     - type: entities
      #       entities:
      #         - entity: lock.big_car_charger_door_lock
      #           name: Charger door lock
      #         - entity: switch.big_car_charger_switch
      #           name: Charger switch
      #         - entity: lock.big_car_door_lock
      #           name: Door lock
      #         - entity: button.big_car_flash_lights
      #           name: Flash lights
      #         - entity: lock.big_car_frunk_lock
      #           name: Frunk lock
      #         - entity: select.big_car_heated_seat_left
      #           name: Heated seat left
      #         - entity: select.big_car_heated_seat_rear_center
      #           name: Heated seat rear_center
      #         - entity: select.big_car_heated_seat_rear_left
      #           name: Heated seat rear_left
      #         - entity: select.big_car_heated_seat_rear_right
      #           name: Heated seat rear_right
      #         - entity: select.big_car_heated_seat_right
      #           name: Heated seat right
      #         - entity: switch.big_car_heated_steering_switch
      #           name: Heated steering switch
      #         - entity: button.big_car_horn
      #           name: Horn
      #         - entity: switch.big_car_maxrange_switch
      #           name: Maxrange switch
      #         - entity: switch.big_car_polling_switch
      #           name: Polling switch
      #         - entity: switch.big_car_sentry_mode_switch
      #           name: Sentry mode switch
      #         - entity: lock.big_car_trunk_lock
      #           name: Trunk lock
      #       title: Big Car
      #     - type: thermostat
      #       entity: climate.big_car_hvac_climate_system

  - icon: mdi:home-assistant
    # Title of the view. Will be used as the tooltip for tab icon
    title: Automations
    cards:
      - type: custom:auto-entities
        card:
          type: entities
          title: Automations
        filter:
          include:
            - entity_id: "automation.*"
  # Specify a tab icon if you want the view tab to be an icon.
