title: Westridge

#
# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
# background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
views:
  # View tab title.
  - icon: mdi:home
    title: Home
    # Optional unique id for direct access /lovelace/${id}
    id: home
    # Optional background (overwrites the global background).
    # background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    # theme: dark-mode
    # The cards to show on this view.
    cards:
      # Show update card if there are updates
      - type: conditional
        conditions:
          - entity: binary_sensor.updater
            state: "on"
        card:
          type: entities
          entities:
            - sensor.latest_version

      - type: vertical-stack
        cards:
          - type: entities
            # Title of the entities card
            title: Switches
            # The entities here will be shown in the same order as specified.
            # Each entry is an entity ID or a map with extra options.
            show_header_toggle: false
            state_color: true
            entities:
              - script.open_gate_temporarily
              - switch.gate
              - cover.ratgdov25i_0b0617_door
              - lock.touchscreen_deadbolt
              - switch.ecm
              - switch.water_heater_recirc_pump
              - switch.dehumidifier
              - script.goodnight

          - type: tile
            entity: switch.mediabox
            features_position: bottom
            vertical: false
            icon_tap_action:
              action: toggle

          - type: tile
            entity: remote.harmony_hub
            features_position: bottom
            vertical: false
            icon_tap_action:
              action: toggle

          # - type: entities
          #   title: Media
          #   state_color: true
          #   entities:
          #     - switch.mediabox
          #     - remote.harmony_hub

          - type: tile
            entity: media_player.denon_avr_x3800h
            features_position: bottom
            vertical: false
            icon_tap_action:
              action: toggle
            features:
              - type: media-player-volume-slider

      - type: tile
        entity: fan.great_room_fan
        features_position: bottom
        features:
          - type: fan-speed

      - type: tile
        entity: fan.master_fan
        features_position: bottom
        features:
          - type: fan-speed

      - type: entities
        title: Lights
        state_color: true
        entities:
          - light.front_hallway_kitchen
          - light.front_hallway_great_room
          - switch.tasmota_sofa
          - light.back_hallway_lights
          - light.dining_room_dining_room
          - light.front_hallway_hallway
          - light.front_door_lights
          - light.front_door_garage
          - light.great_room_patio_lights
          - switch.kep_lights
          - switch.meimei_lights
          # - switch.front_door_xmas_lights
          # - switch.front_door_figures
          # - switch.garage_xmas_lights

      - type: vertical-stack
        cards:
          - type: entities
            title: People
            show_header_toggle: false
            entities:
              - person.cam
              - person.sandy
              - group.guests
              - input_select.occupants

          - type: tile
            entity: alarm_control_panel.home_alarm
            features_position: inline
            features:
              - type: alarm-modes
                modes:
                  - armed_home
                  - armed_away
                  - disarmed
            name: !secret alarm_name

          - type: entity
            entity: sensor.alarm_status_with_zone_name
            name: false
            icon: none
            card_mod:
              style: |
                ha-card .header {
                  display: none;
                }
                ha-card .info {
                  width: 100%;
                  padding-top: 16px;
                  margin-top: 0px;
                }
                ha-card .value {
                  font-size: 18px !important;
                }

  - icon: mdi:weather-partly-snowy-rainy
    title: Climate
    id: climate
    cards:
      - type: weather-forecast
        entity: weather.pirateweather
        forecast_type: daily
      - type: entities
        title: Climate
        show_header_toggle: false
        state_color: true
        entities:
          - input_select.climate_mode
          - input_number.climate_temp
          # - climate.front
          - climate.mitp_heat_pump_3b2a04_front_climate
          - climate.mitp_heat_pump_3b2a10_back_climate
          - sensor.weather_local_inside_temperature
          - sensor.weather_local_outside_temperature
          - input_boolean.master_floor_heat
          - input_boolean.kids_floor_heat
          - input_boolean.guest_floor_heat

      - type: tile
        entity: fan.great_room_fan
        features_position: bottom
        features:
          - type: fan-speed

      - type: tile
        entity: fan.master_fan
        features_position: bottom
        features:
          - type: fan-speed

      - type: entities
        title: Dining Shades
        show_header_toggle: false
        entities:
          - cover.dining_room_front
          - cover.dining_room_side
          - script.open_dining_shades_full
          - script.open_dining_shades_half
          - script.close_dining_shades

      - type: entities
        title: Master Shades
        show_header_toggle: false
        entities:
          - cover.master_back_left
          - cover.master_back_right
          - cover.master_big_window
          - script.open_master_shades_full
          - script.open_master_shades_half
          - script.close_master_shades

  # Specify a tab icon if you want the view tab to be an icon.
  - icon: mdi:solar-power
    title: Solar
    id: solar
    cards:
      - type: custom:auto-entities
        card:
          type: entities
          title: Solar
        filter:
          include:
            - entity_id: "sensor.solar*"
        sort:
          method: name
      - type: custom:auto-entities
        card:
          type: entities
          title: Gateways
        filter:
          include:
            - entity_id: "sensor.envoy*"
        sort:
          method: name
