title: Westridge
# Include external resources
resources:
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    type: module
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module

#
# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
# background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
views:
  # View tab title.
  - icon: mdi:home
    title: Home
    # Optional unique id for direct access /lovelace/${id}
    id: home
    # Optional background (overwrites the global background).
    # background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    # theme: dark-mode
    # The cards to show on this view.
    cards:
      # Show update card if there are updates
      - type: conditional
        conditions:
          - entity: binary_sensor.updater
            state: "on"
        card:
          type: entities
          entities:
            - sensor.latest_version

      - type: entities
        # Title of the entities card
        title: Switches
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        show_header_toggle: false
        state_color: true
        entities:
          - script.open_gate_temporarily
          - switch.gate
          - lock.be469
          - switch.water_heater_recirc_pump
          - switch.kep_lights
          - switch.meimei_lights
          - switch.great_room_fan
          - switch.ecm
          - switch.wemo_dehumidifier
          - switch.mediabox
          - remote.harmony_hub
          - script.goodnight

      - type: entities
        title: People
        show_header_toggle: false
        entities:
          - person.cam
          - person.sandy
          - group.camsandy
          - group.guests
          - input_select.occupants

      - type: entities
        title: Lights
        state_color: true
        entities:
          - light.front_hallway_kitchen
          - light.front_hallway_great_room
          - light.back_hallway_lights
          - light.dining_room_dining_room
          - light.front_hallway_hallway
          - light.front_door_lights
          - light.front_door_garage
          - light.great_room_patio_lights
          - switch.front_door_xmas_lights
          - switch.front_door_figures
          - switch.garage_xmas_lights
          - switch.great_room_fan

      - type: entities
        title: Climate
        show_header_toggle: false
        state_color: true
        entities:
          - input_select.climate_mode
          - input_number.climate_temp
          - climate.front
          - climate.back
          - sensor.westridge_inside_temp
          - sensor.westridge_temp
          - input_boolean.master_floor_heat
          - input_boolean.kids_floor_heat
          - input_boolean.guest_floor_heat

      - type: entities
        title: Dining Shades
        show_header_toggle: false
        entities:
          - cover.dining_room_front
          - cover.dining_room_side
          - script.open_dining_shades_full
          - script.open_dining_shades_half
          - script.close_dining_shades

      - type: entities
        title: Master Shades
        show_header_toggle: false
        entities:
          - cover.master_back_left
          - cover.master_back_right
          - cover.master_big_window
          - script.open_master_shades_full
          - script.open_master_shades_half
          - script.close_master_shades

      - type: entities
        entities:
          - entity: cover.ratgdov25i_0b0617_door
            name: door
          - entity: button.ratgdov25i_0b0617_toggle_door
            name: toggle door
        title: Garage Door

      - type: alarm-panel
        entity: alarm_control_panel.home_alarm
        show_keypad: false
        title: Alarm
        states:
          - arm_away

      - type: weather-forecast
        entity: weather.pirateweather
        forecast_type: daily

      - type: custom:mini-media-player
        entity: media_player.lg_webos_tv_b36b

      - type: custom:mini-media-player
        entity: media_player.marantz_sr5012_2

      - type: entities
        title: Solar
        show_header_toggle: false
        entities:
          - sensor.enphase

  # Specify a tab icon if you want the view tab to be an icon.
  - title: Sensors
    id: sensors
    cards:
      - type: entities
        title: Climate Other
        show_header_toggle: false
        entities:
          - climate.master_nuheat
          - climate.kids_nuheat
          - climate.guest_nuheat
      - type: entities
        entities:
          - binary_sensor.elara_bedroom
          - binary_sensor.front_door
          - binary_sensor.front_windows
          - binary_sensor.guest_bedroom
          - binary_sensor.hall_bath
          - binary_sensor.kep_bedroom
          - binary_sensor.kitchen
          - binary_sensor.laundry
          - binary_sensor.lift_slide
          - binary_sensor.master
          - binary_sensor.master_bath
          - binary_sensor.mudroom_powder
          - binary_sensor.pantry
          - binary_sensor.fire_sprinklers
          - entity: binary_sensor.home_alarm_ready
            name: Ready
          - entity: sensor.home_alarm_keypad
            name: Keypad
          - entity: binary_sensor.home_alarm_alarm
            name: Alarm
          - entity: binary_sensor.home_alarm_fire
            name: Fire
        title: Home Alarm

      - type: custom:auto-entities
        card:
          type: entities
          title: Weather Station
        filter:
          include:
            - entity_id: "sensor.westridge*"
        sort:
          method: name
      - type: custom:auto-entities
        card:
          type: entities
          title: Zwave
        filter:
          include:
            - entity_id: "zwave.*"
        sort:
          method: name
      - type: custom:auto-entities
        card:
          type: entities
          title: Tasmota
        filter:
          include:
            - entity_id: "sensor.tasmota.*"
        sort:
          method: name
      - type: grid
        square: false
        columns: 1
        cards:
          - type: entities
            entities:
              - entity: lock.big_car_charger_door_lock
                name: Charger door lock
              - entity: switch.big_car_charger_switch
                name: Charger switch
              - entity: lock.big_car_door_lock
                name: Door lock
              - entity: button.big_car_flash_lights
                name: Flash lights
              - entity: lock.big_car_frunk_lock
                name: Frunk lock
              - entity: select.big_car_heated_seat_left
                name: Heated seat left
              - entity: select.big_car_heated_seat_rear_center
                name: Heated seat rear_center
              - entity: select.big_car_heated_seat_rear_left
                name: Heated seat rear_left
              - entity: select.big_car_heated_seat_rear_right
                name: Heated seat rear_right
              - entity: select.big_car_heated_seat_right
                name: Heated seat right
              - entity: switch.big_car_heated_steering_switch
                name: Heated steering switch
              - entity: button.big_car_horn
                name: Horn
              - entity: switch.big_car_maxrange_switch
                name: Maxrange switch
              - entity: switch.big_car_polling_switch
                name: Polling switch
              - entity: switch.big_car_sentry_mode_switch
                name: Sentry mode switch
              - entity: lock.big_car_trunk_lock
                name: Trunk lock
            title: Big Car
          - type: thermostat
            entity: climate.big_car_hvac_climate_system

  # Specify a tab icon if you want the view tab to be an icon.
  - title: Solar
    id: solar
    cards:
      - type: custom:auto-entities
        card:
          type: entities
          title: Solar
        filter:
          include:
            - entity_id: "sensor.solar*"
        sort:
          method: name
      - type: custom:auto-entities
        card:
          type: entities
          title: Gateways
        filter:
          include:
            - entity_id: "sensor.envoy*"
        sort:
          method: name

  - icon: mdi:home-assistant
    # Title of the view. Will be used as the tooltip for tab icon
    title: Automations
    cards:
      - type: custom:auto-entities
        card:
          type: entities
          title: Automations
        filter:
          include:
            - entity_id: "automation.*"
