- alias: Dehumidifier on if below 44 F
  initial_state: True
  hide_entity: False
  trigger:
    platform: numeric_state
    entity_id: weather.dark_sky
    value_template: "{{ state.attributes.temperature }}"
    below: '44'
  condition:
    condition: numeric_state
    entity_id: sensor.bedrooms_thermostat_hallway_humidity
    above: '40'
  action:
    entity_id: switch.wemo
    service: switch.turn_on

- alias: Dehumidifier off if above 50 F
  initial_state: True
  hide_entity: False
  trigger:
    platform: numeric_state
    entity_id: weather.dark_sky
    value_template: "{{ state.attributes.temperature }}"
    above: '50'
  action:
    entity_id: switch.dehumidifier
    service: switch.turn_off

