# - alias: ECM on at 1345
#   initial_state: True
#   trigger:
#     - platform: time
#       at: '13:45:00'
#   condition:
#     condition: state
#     entity_id: person.cam
#     state: 'home'
#   action:
#     entity_id: switch.ecm
#     service: switch.turn_on

- alias: ECM on at 0650
  initial_state: True
  trigger:
    - platform: time
      at: '06:50:00'
  condition:
    condition: state
    entity_id: group.camsandy
    state: 'home'
  action:
    entity_id: switch.ecm
    service: switch.turn_on


