# Presence detection can be a little slow so disarm alarm when the garage door is opened
- alias: Garage - Disarm when garage door is opened
  initial_state: False
  trigger:
    platform: state
    entity_id: cover.garage_door_opener
    from: "closed"
    to: "open"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: "armed_away"
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: "armed_home"
  action:
    service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.home_alarm

- alias: Garage - Notify if setting away and door left open
  initial_state: true
  trigger:
    platform: state
    entity_id: group.people
    from: "home"
    to: "not_home"
  condition:
    - condition: state
      entity_id: cover.ratgdov25i_0b0617_door
      state: "open"
  action:
    - service: notify.push_family
      data:
        message: "Garage left open"

- id: garage_open_on_school_day
  alias: Garage - Open on school day
  trigger:
    - platform: time
      at: "07:25:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: group.camsandy
      state: "home"
    - condition: state
      entity_id: binary_sensor.school_holiday
      state: "off"
    - condition: state
      entity_id: binary_sensor.school_year
      state: "on"
  action:
    - service: cover.open_cover
      target:
        entity_id: cover.ratgdov25i_0b0617_door

- id: garage_open_on_piano_lessons
  alias: Garage - Open on piano lessons day
  trigger:
    - platform: time
      at: "08:30:00"
  condition:
    - condition: time
      weekday:
        - sun
    - condition: state
      entity_id: group.camsandy
      state: "home"
    - condition: state
      entity_id: binary_sensor.piano_lessons
      state: "on"
  action:
    - service: cover.open_cover
      target:
        entity_id: cover.ratgdov25i_0b0617_door

- id: garage_open_on_art_class_day
  alias: Garage - Open on art class day
  trigger:
    - platform: time
      at: "08:30:00"
  condition:
    - condition: time
      weekday:
        - sat
        - sun
    - condition: state
      entity_id: group.camsandy
      state: "home"
    - condition: state
      entity_id: binary_sensor.art_class
      state: "on"
  action:
    - service: cover.open_cover
      target:
        entity_id: cover.ratgdov25i_0b0617_door
