# Presence detection can be a little slow so disarm alarm when the garage door is opened
- alias: Garage - Disarm when garage door is opened
  initial_state: True
  trigger:
    platform: state
    entity_id: cover.garage_door_opener
    from: 'closed'
    to: 'open'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: 'armed_away'
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: 'armed_home'
  action:
    service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.home_alarm

- alias: Garage - Notify if setting away and door left open
  initial_state: True
  trigger:
    platform: state
    entity_id: group.people
    from: 'home'
    to: 'not_home'
  condition:
    - condition: state
      entity_id: cover.garage_door_opener
      state: 'open'
  action:
    - service: notify.push_family
      data:
        message: "Garage left open"
