- alias: If in cool mode and left home, set temp to 80
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: group.people
    from: 'home'
    to: 'not_home'
  condition:
    - condition: state
      entity_id: input_select.occupants
      state: 'auto'
    - condition: state
      entity_id: input_select.climate_mode
      state: 'cool'
  action:
    service: script.set_temperature_and_notify
    data:
      temperature: 80
      message: 'House empty, setting AC to 80'


- alias: Turn off guest/dog mode when we get back home
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: group.people
    from: 'not_home'
    to: 'home'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.occupants
        option: 'auto'


- alias: If in cool mode and 5pm and not home, set temp to 70
  initial_state: True
  hide_entity: False
  trigger:
    - platform: time
      at: '17:00:00'
  condition:
    - condition: state
      entity_id: input_select.occupants
      state: 'auto'
    - condition: state
      entity_id: input_select.climate_mode
      state: 'cool'
    - condition: state
      entity_id: group.people
      state: 'not_home'
  action:
    service: script.set_temperature_and_notify
    data:
      temperature: 70
      message: '5pm, precooling AC to 70'


- alias: If in cool mode and arrived home, set temp to 70
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: group.people
      from: 'not_home'
      to: 'home'
  condition:
    - condition: state
      entity_id: input_select.occupants
      state: 'auto'
    - condition: state
      entity_id: input_select.climate_mode
      state: 'cool'
  action:
    service: script.set_temperature_and_notify
    data:
      temperature: 70
      message: 'Welcome home, setting AC to 70'


- alias: If in heat mode and left home, set temp to 60
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: group.people
    from: 'home'
    to: 'not_home'
  condition:
    - condition: state
      entity_id: input_select.occupants
      state: 'auto'
    - condition: state
      entity_id: input_select.climate_mode
      state: 'heat'
  action:
    service: script.set_temperature_and_notify
    data:
      temperature: 60
      message: 'Goodbye, setting heat to 60'


- alias: If in heat mode and arrived home, set temp to 70
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: group.people
      from: 'not_home'
      to: 'home'
  condition:
    - condition: state
      entity_id: input_select.occupants
      state: 'auto'
    - condition: state
      entity_id: input_select.climate_mode
      state: 'heat'
  action:
    service: script.set_temperature_and_notify
    data:
      temperature: 70
      message: 'Welcome home, setting heat to 70'


# If in heat mode and we're home, set temp to 70 at 7:30am
- alias: Turn on heat in the morning
  initial_state: True
  hide_entity: False
  trigger:
    - platform: time
      at: '07:30:00'
  condition:
    - condition: state
      entity_id: sensor.entryway_thermostat_operation_mode
      state: 'heat'
    - condition: state
      entity_id: group.people
      state: 'home'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_select.occupants
          state: 'auto'
        - condition: state
          entity_id: input_select.occupants
          state: 'dogs'
        - condition: state
          entity_id: input_select.occupants
          state: 'guests'
  action:
    service: script.set_temperature
    data:
      temperature: 70

# If in heat mode and we're home, set LR temp to 70 at 6:30am
- alias: Turn on heat in the morning
  initial_state: True
  hide_entity: False
  trigger:
    - platform: time
      at: '06:30:00'
  condition:
    - condition: state
      entity_id: sensor.entryway_thermostat_operation_mode
      state: 'heat'
    - condition: state
      entity_id: group.people
      state: 'home'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_select.occupants
          state: 'auto'
        - condition: state
          entity_id: input_select.occupants
          state: 'dogs'
        - condition: state
          entity_id: input_select.occupants
          state: 'guests'
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.entryway
      operation_mode: 'heat'
      temperature: '70'

# If in heat mode, set temp front to 60 at 1am
- alias: Turn off front heat at night
  initial_state: True
  hide_entity: False
  trigger:
    - platform: time
      at: '01:00:00'
  condition:
    - condition: state
      entity_id: sensor.entryway_thermostat_operation_mode
      state: 'heat'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_select.occupants
          state: 'auto'
        - condition: state
          entity_id: input_select.occupants
          state: 'dogs'
        - condition: state
          entity_id: input_select.occupants
          state: 'guests'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.entryway
        operation_mode: 'heat'
        temperature: '60'

# If in heat mode, set temp at back to 68 at midnight
- alias: Set back heat to 68 at night
  initial_state: True
  hide_entity: False
  trigger:
    - platform: time
      at: '00:00:00'
  condition:
    - condition: state
      entity_id: sensor.entryway_thermostat_operation_mode
      state: 'heat'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_select.occupants
          state: 'auto'
        - condition: state
          entity_id: input_select.occupants
          state: 'dogs'
        - condition: state
          entity_id: input_select.occupants
          state: 'guests'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.bedrooms_hallway
        operation_mode: 'heat'
        temperature: '68'

# These four automations bind the UI to the Nest and vice versa
- alias: Set operation mode based on UI
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: input_select.climate_mode
  action:
    - service: climate.set_operation_mode
      data_template:
        entity_id: climate.entryway
        operation_mode: '{{ states.input_select.climate_mode.state }}'
    - service: climate.set_operation_mode
      data_template:
        entity_id: climate.bedrooms_hallway
        operation_mode: '{{ states.input_select.climate_mode.state }}'
    # if we're not in eco, set temp (nest doesn't let you set temp in eco mode)
    - condition: or
      conditions:
      - condition: state
        entity_id: input_select.climate_mode
        state: 'heat'
      - condition: state
        entity_id: input_select.climate_mode
        state: 'cool'
      - condition: state
        entity_id: input_select.climate_mode
        state: 'auto'
    - delay: '00:00:10'
    - service: script.set_temperature_and_notify
      data_template:
        temperature: '{{ states.input_number.climate_temp.state | float }}'
        message: 'Setting HVAC to {{ states.input_number.climate_temp.state }} (mode: {{ states.input_select.climate_mode.state }})'

- alias: Set temperature based on UI
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: input_number.climate_temp
  condition:
    condition: or
    conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: sensor.bedrooms_thermostat_hallway_operation_mode
          state: 'heat'
        - condition: numeric_state
          entity_id: input_number.climate_temp
          below: '72'
      - condition: and
        conditions:
        - condition: state
          entity_id: sensor.bedrooms_thermostat_hallway_operation_mode
          state: 'cool'
        - condition: numeric_state
          entity_id: input_number.climate_temp
          above: '68'
  action:
    - service: script.set_temperature_and_notify
      data_template:
        temperature: '{{ states.input_number.climate_temp.state | float }}'
        message: 'Setting HVAC to {{ states.input_number.climate_temp.state }} (mode: {{ states.input_select.climate_mode.state }})'

# - alias: Set operation mode from the Nest
#   initial_state: True
#   hide_entity: False
#   trigger:
#     - platform: state
#       entity_id: sensor.bedrooms_thermostat_hallway_operation_mode
#   action:
#     - service: input_select.select_option
#       data_template:
#         entity_id: input_select.climate_mode
#         option: '{{ states.sensor.bedrooms_thermostat_hallway_operation_mode.state }}'
#
# - alias: Set temperature from the Nest
#   initial_state: True
#   hide_entity: False
#   trigger:
#     - platform: state
#       entity_id: sensor.bedrooms_thermostat_hallway_target
#   action:
#     - service: input_number.set_value
#       data_template:
#         entity_id: input_number.climate_temp
#         value: '{{ states.sensor.bedrooms_thermostat_hallway_target.state }}'
#

- alias: Set operation mode on startup
  initial_state: True
  hide_entity: False
  trigger:
    platform: homeassistant
    event: start
  action:
    service: input_select.select_option
    entity_id: input_select.climate_mode
    data_template:
      option: '{{ states.sensor.bedrooms_thermostat_hallway_operation_mode.state }}'
