# If in heat mode and we're home, set temp to 73 at 6:30am
- alias: HVAC - Turn up front heat in the morning
  id: hvac_morning_front_heat_up
  initial_state: True
  trigger:
    - platform: time
      at: "05:00:00"
  condition:
    - condition: state
      entity_id: climate.front
      state: "heat"
    - condition: or
      conditions:
        - condition: state
          entity_id: group.people
          state: "home"
        - condition: state
          entity_id: input_select.occupants
          state: "dogs"
        - condition: state
          entity_id: input_select.occupants
          state: "guests"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.front
      hvac_mode: "heat"
      temperature: 68

# Turn up heat in the bedrooms later
- alias: HVAC - Turn up back heat in the morning
  id: hvac_morning_back_heat_up
  initial_state: False
  trigger:
    - platform: time
      at: "08:00:00"
  condition:
    - condition: state
      entity_id: climate.back
      state: "heat"
    - condition: or
      conditions:
        - condition: state
          entity_id: group.people
          state: "home"
        - condition: state
          entity_id: input_select.occupants
          state: "dogs"
        - condition: state
          entity_id: input_select.occupants
          state: "guests"
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.back
      hvac_mode: "heat"
      temperature: 70

# If in heat mode, set temp front to 65 at night
- alias: HVAC - Turn off front heat at night
  id: hvac_evening_front_heat_down
  initial_state: True
  trigger:
    - platform: time
      at: "00:30:00"
  condition:
    - condition: state
      entity_id: climate.front
      state: "heat"
    - condition: or
      conditions:
        - condition: state
          entity_id: group.people
          state: "home"
        - condition: state
          entity_id: input_select.occupants
          state: "dogs"
        - condition: state
          entity_id: input_select.occupants
          state: "guests"
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.front
        hvac_mode: "heat"
        temperature: "65"

# If in heat mode, set temp at back to 64 at midnight
- alias: HVAC - Set back heat to 64 at 10pm
  id: hvac_evening_back_heat_down
  initial_state: True
  trigger:
    - platform: time
      at: "22:00:00"
  condition:
    - condition: state
      entity_id: climate.back
      state: "heat"
    - condition: or
      conditions:
        - condition: state
          entity_id: group.people
          state: "home"
        - condition: state
          entity_id: input_select.occupants
          state: "dogs"
        - condition: state
          entity_id: input_select.occupants
          state: "guests"
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.back
        hvac_mode: "heat"
        temperature: "64"

# These automations bind the UI to the Thermostat and vice versa
- id: hvac_set_mode_from_ui
  alias: "HVAC - Set hvac mode based on UI"
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.climate_mode
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: input_select.climate_mode
          state: "heat"
        - condition: state
          entity_id: input_select.climate_mode
          state: "cool"
        - condition: state
          entity_id: input_select.climate_mode
          state: "off"
  action:
    - service: climate.set_hvac_mode
      data_template:
        entity_id: climate.front
        hvac_mode: "{{ states.input_select.climate_mode.state }}"
    - service: climate.set_hvac_mode
      data_template:
        entity_id: climate.back
        hvac_mode: "{{ states.input_select.climate_mode.state }}"

- id: hvac_set_mode_from_ui_fan_only
  alias: "HVAC - Set hvac mode to fan only based on UI"
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.climate_mode
  condition:
    - condition: state
      entity_id: input_select.climate_mode
      state: "fan only"
  action:
    - service: climate.set_hvac_mode
      data_template:
        entity_id: climate.front
        hvac_mode: "fan_only"
    - service: climate.set_hvac_mode
      data_template:
        entity_id: climate.back
        hvac_mode: "fan_only"

- id: hvac_set_temp_from_ui
  alias: HVAC - Set temperature based on UI
  initial_state: True
  trigger:
    platform: state
    entity_id: input_number.climate_temp
  condition:
    condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: sensor.front_thermostat_operation_mode
            state: "heat"
          - condition: numeric_state
            entity_id: input_number.climate_temp
            below: "69"
      - condition: and
        conditions:
          - condition: state
            entity_id: sensor.front_thermostat_operation_mode
            state: "cool"
          - condition: numeric_state
            entity_id: input_number.climate_temp
            above: "66"
  action:
    - service: script.set_temperature_and_notify
      data_template:
        temperature: "{{ states.input_number.climate_temp.state | float }}"
        message: "Setting HVAC to {{ states.input_number.climate_temp.state }} (mode: {{ states.input_select.climate_mode.state }})"

# - id: hvac_set_mode_on_startup
#   alias: HVAC - Set hvac mode on startup
#   initial_state: True
#   trigger:
#     platform: homeassistant
#     event: start
#   action:
#     - service: input_select.select_option
#       entity_id: input_select.climate_mode
#       data_template:
#         option: '{{ states.sensor.front_thermostat_operation_mode.state }}'

- id: hvac_set_temp_on_startup
  alias: HVAC - Set hvac temp on startup
  initial_state: false
  trigger:
    platform: homeassistant
    event: start
  condition:
  not:
    - condition: state
      entity_id: states.sensor.front_thermostat_operation_mode
      state: "off"
  action:
    - service: input_number.set_value
      entity_id: input_number.climate_temp
      data_template:
        value: "{{ states.sensor.back_thermostat_target.state }}"
