# random notes
# if it's more than 78 outside
# and it's more than 76 inside, turn on ac

# if house is unoccupied, set eco
# if house is occupied and inside temp is above 72 and outside temp is above 72, set cool
# if house is unoccupied and temp is below


- alias: Set eco mode when house is empty
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: group.people
    from: 'home'
    to: 'not_home'
  condition:
    condition: state
    entity_id: input_select.occupants
    state: 'none'
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.entryway
        operation_mode: 'eco'
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedrooms_hallway
        operation_mode: 'eco'
    - service: notify.gmail
      data:
        title: 'House empty, set to eco mode'
        message: 'House empty, set to eco mode'


# Set HVAC to cool when we get home
# or at 5pm
# and it's hotter than 74 outside and 74 inside
# and the state is still eco
# TODO? should this set the inputs instead of talking to the nests directly?
- alias: Set cool mode when we come home
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: group.people
      from: 'not_home'
      to: 'home'
    - platform: time
      at: '17:00:00'
  condition:
    - condition: numeric_state
      entity_id: sensor.pws_temp_f
      above: '74'
    - condition: numeric_state
      entity_id: sensor.bedrooms_thermostat_hallway_temperature
      above: '74'
    - condition: state
      entity_id: sensor.bedrooms_thermostat_hallway_operation_mode
      state: 'eco'
  action:
    - service: climate.set_operation_mode
      data_template:
        entity_id: climate.entryway
        operation_mode: 'cool'
    - service: climate.set_operation_mode
      data_template:
        entity_id: climate.bedrooms_hallway
        operation_mode: 'cool'
    - delay: '00:00:10'
    - service: climate.set_temperature
      data:
        entity_id: climate.entryway
        operation_mode: 'cool'
        temperature: '74'
    - service: climate.set_temperature
      data:
        entity_id: climate.bedrooms_hallway
        operation_mode: 'cool'
        temperature: '74'
    - service: notify.gmail
      data:
        title: 'Set to cool'
        message: 'It is hot, setting to cool mode'

# Set HVAC to heat when we get home
# or at 6pm
# and it's colder than 60 outside and 67 inside
# and the state is still eco
- alias: Set heat mode when we come home
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: group.people
      from: 'not_home'
      to: 'home'
    - platform: time
      at: '18:00:00'
  condition:
    - condition: numeric_state
      entity_id: sensor.pws_temp_f
      below: '60'
    - condition: numeric_state
      entity_id: sensor.bedrooms_thermostat_hallway_temperature
      below: '67'
    - condition: state
      entity_id: sensor.bedrooms_thermostat_hallway_operation_mode
      state: 'eco'
  action:
    - service: climate.set_operation_mode
      data_template:
        entity_id: climate.entryway
        operation_mode: 'heat'
    - service: climate.set_operation_mode
      data_template:
        entity_id: climate.bedrooms_hallway
        operation_mode: 'heat'
    - delay: '00:00:10'
    - service: climate.set_temperature
      data:
        entity_id: climate.entryway
        operation_mode: 'heat'
        temperature: '70'
    - service: climate.set_temperature
      data:
        entity_id: climate.bedrooms_hallway
        operation_mode: 'heat'
        temperature: '70'
    - service: notify.gmail
      data:
        title: 'Set to heat'
        message: 'It is cold, set to heat mode'

# These four automations bind the UI to the Nest and vice versa
- alias: Set operation mode based on UI
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: input_select.climate_mode
  action:
    - service: climate.set_operation_mode
      data_template:
        entity_id: climate.entryway
        operation_mode: '{{ states.input_select.climate_mode.state }}'
    - service: climate.set_operation_mode
      data_template:
        entity_id: climate.bedrooms_hallway
        operation_mode: '{{ states.input_select.climate_mode.state }}'
    # if we're not in eco, set temp (nest doesn't let you set temp in eco mode)
    - condition: or
      conditions:
      - condition: state
        entity_id: input_select.climate_mode
        state: 'heat'
      - condition: state
        entity_id: input_select.climate_mode
        state: 'cool'
      - condition: state
        entity_id: input_select.climate_mode
        state: 'auto'
    - delay: '00:00:10'
    - service: climate.set_temperature
      data_template:
        entity_id: climate.entryway
        temperature: '{{ states.input_number.climate_temp.state | float }}'
    - service: climate.set_temperature
      data_template:
        entity_id: climate.bedrooms_hallway
        temperature: '{{ states.input_number.climate_temp.state | float }}'

- alias: Set temperature based on UI
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: input_number.climate_temp
  condition:
    # can't set temperature when in eco mode
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.bedrooms_thermostat_hallway_operation_mode
        state: 'heat'
      - condition: state
        entity_id: sensor.bedrooms_thermostat_hallway_operation_mode
        state: 'cool'
      - condition: state
        entity_id: sensor.bedrooms_thermostat_hallway_operation_mode
        state: 'auto'
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.entryway
        operation_mode: '{{ states.input_select.climate_mode.state }}'
        temperature: '{{ states.input_number.climate_temp.state | float }}'
    - service: climate.set_temperature
      data_template:
        entity_id: climate.bedrooms_hallway
        operation_mode: '{{ states.input_select.climate_mode.state }}'
        temperature: '{{ states.input_number.climate_temp.state | float }}'

- alias: Set operation mode from the Nest
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: sensor.bedrooms_thermostat_hallway_operation_mode
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.climate_mode
        option: '{{ states.sensor.bedrooms_thermostat_hallway_operation_mode.state }}'

- alias: Set temperature from the Nest
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: sensor.bedrooms_thermostat_hallway_target
  action:
    - service: input_number.select_value
      data_template:
        entity_id: input_number.climate_temp
        value: '{{ states.sensor.bedrooms_thermostat_hallway_target.state }}'

