- alias: Lights - Turn on patio when sliding door is opened
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.lift_slide
    from: "off"
    to: "on"
  condition:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
    - condition: state
      entity_id: light.great_room_patio_lights
      state: "off"
  action:
    - service: light.turn_on
      entity_id: light.great_room_patio_lights
    - delay: "00:05:00"
    - service: light.turn_off
      entity_id: light.great_room_patio_lights

- alias: Lights - If we arrived home, turn on garage / front door lights
  id: lights_turn_on_arrive_home
  initial_state: True
  trigger:
    - platform: state
      entity_id: group.people
      to: "home"
    - platform: state
      entity_id: person.cam
      to: "home"
    - platform: state
      entity_id: person.sandy
      to: "home"
  condition:
    - condition: or
      conditions:
        - condition: sun
          after: sunset
          after_offset: "-02:00:00"
        - condition: numeric_state
          entity_id: sensor.westridge_solar_rad_lx
          below: 20000
  action:
    - service: light.turn_on
      entity_id:
        - light.front_door_lights
        - light.front_door_garage
        - light.front_hallway_hallway
        - light.front_hallway_great_room
        - light.front_hallway_kitchen
        - light.dining_room_dining_room

- alias: Lights - Turn off when we leave
  initial_state: True
  trigger:
    - platform: state
      entity_id: group.people
      from: "home"
      to: "not_home"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: input_select.occupants
          state: "auto"
        - condition: state
          entity_id: input_select.occupants
          state: "dogs"
  action:
    - service: light.turn_off
      entity_id:
        - light.front_door_lights
        - light.front_door_garage
        - light.front_hallway_hallway
        - light.front_hallway_great_room
        - light.front_hallway_kitchen
        - light.dining_room_dining_room

- alias: Lights - Xmas lights on at 4:30pm
  initial_state: True
  trigger:
    - platform: time
      at: "16:30:00"
  action:
    service: switch.turn_on
    data:
      entity_id:
        - switch.front_door_figures
        - switch.garage_xmas_lights
        # - switch.front_door_xmas_lights

- alias: Lights - Xmas lights off at 2am
  initial_state: True
  trigger:
    - platform: time
      at: "2:00:00"
  action:
    service: switch.turn_off
    data:
      entity_id:
        - switch.front_door_figures
        - switch.garage_xmas_lights
        # - switch.front_door_xmas_lights
