- alias: Turn on patio lights when sliding door is opened
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: binary_sensor.lift__slide
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: light.great_room_patio_lights
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.great_room_patio_lights
    - delay: '00:05:00'
    - service: light.turn_off
      entity_id: light.great_room_patio_lights

