- alias: Lights - Turn on patio when sliding door is opened
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: binary_sensor.lift__slide
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: light.great_room_patio_lights
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.great_room_patio_lights
    - delay: '00:05:00'
    - service: light.turn_off
      entity_id: light.great_room_patio_lights


- alias: Lights - If we arrived home, turn on garage / front door lights
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: group.people
      from: 'not_home'
      to: 'home'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: light.turn_on
      entity_id: light.front_door_lights
    - service: light.turn_on
      entity_id: light.front_door_garage
