- alias: Nightly - Notify if garage, door, or gate are open
  initial_state: True
  trigger:
    - platform: time
      at: '23:30:00'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: lock.be469
          state: 'unlocked'
        - condition: state
          entity_id: switch.gate
          state: 'on'
  action:
    - service: notify.push_family
      data_template:
        message: >
          Left open:
          {%- if is_state("lock.be469", "unlocked") %}
            {{ states.lock.be469.attributes.friendly_name }}
          {%- endif -%}
          {%- if is_state("switch.gate", "on") %}
            {{ states.switch.gate.attributes.friendly_name }}
          {%- endif -%}

