- alias: NuHeat - Turn off when we leave
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: group.camsandy
    from: 'home'
    to: 'not_home'
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.master_floor_heat

- alias: NuHeat - Turn on at 6:15am if we're home
  initial_state: True
  hide_entity: False
  trigger:
    - platform: time
      at: '06:15:00'
  condition:
    - condition: state
      entity_id: group.camsandy
      state: 'home'
    - condition: numeric_state
      entity_id: sensor.bedrooms_thermostat_hallway_temperature
      below: '76'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.master_floor_heat

# if m-f, turn off at 7:30am
- alias: NuHeat - Turn off at 7:45 on M-F
  initial_state: True
  hide_entity: False
  trigger:
    - platform: time
      at: '07:45:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.master_floor_heat

# if ss, turn off at 10am
- alias: NuHeat - Turn off at 10am on SS
  initial_state: True
  hide_entity: False
  trigger:
    - platform: time
      at: '10:00:00'
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.master_floor_heat


# FIXME: don't turn on if inside temp is >= 75 or ac is on
# if we're home and time is 6:30pm, turn on
- alias: NuHeat - Turn on at 6:30pm if we're home
  initial_state: True
  hide_entity: False
  trigger:
    - platform: time
      at: '18:30:00'
  condition:
    - condition: state
      entity_id: group.camsandy
      state: 'home'
    - condition: numeric_state
      entity_id: sensor.bedrooms_thermostat_hallway_temperature
      below: '75'
    - condition: template
      value_template: '{{ states.sensor.bedrooms_thermostat_hallway_operation_mode.state != "cool" }}'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.master_floor_heat

- alias: NuHeat - Turn on when we come home if 6:30pm < now < 11:45pm
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: group.camsandy
    from: 'not_home'
    to: 'home'
  condition:
    - condition: time
      after: '18:30:00'
      before: '23:45:00'
    - condition: numeric_state
      entity_id: sensor.bedrooms_thermostat_hallway_temperature
      below: '75'
    - condition: template
      value_template: '{{ states.sensor.bedrooms_thermostat_hallway_operation_mode.state != "cool" }}'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.master_floor_heat

- alias: NuHeat - Turn off at 11:45pm
  initial_state: True
  hide_entity: False
  trigger:
    - platform: time
      at: '23:45:00'
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.master_floor_heat




- alias: NuHeat - Guest Turn off when not home
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: group.guests
    from: 'home'
    to: 'not_home'
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.guest_floor_heat

- alias: NuHeat - Guest Turn on at 6:15am if home
  initial_state: True
  hide_entity: False
  trigger:
    - platform: time
      at: '06:15:00'
  condition:
    - condition: state
      entity_id: group.guests
      state: 'home'
    - condition: numeric_state
      entity_id: sensor.bedrooms_thermostat_hallway_temperature
      below: '76'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.guest_floor_heat

# if m-f, turn off at 7:30am
- alias: NuHeat - Guest Turn off at 8:30 on M-F
  initial_state: True
  hide_entity: False
  trigger:
    - platform: time
      at: '08:30:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.guest_floor_heat

# if ss, turn off at 10am
- alias: NuHeat - Guest Turn off at 9am on SS
  initial_state: True
  hide_entity: False
  trigger:
    - platform: time
      at: '9:00:00'
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.guest_floor_heat


- alias: NuHeat - Guest Turn on at 6:30pm if home
  initial_state: True
  hide_entity: False
  trigger:
    - platform: time
      at: '18:30:00'
  condition:
    - condition: state
      entity_id: group.guests
      state: 'home'
    - condition: numeric_state
      entity_id: sensor.bedrooms_thermostat_hallway_temperature
      below: '75'
    - condition: template
      value_template: '{{ states.sensor.bedrooms_thermostat_hallway_operation_mode.state != "cool" }}'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.guest_floor_heat

- alias: NuHeat - Guest Turn on when arrive home if 6:30pm < now < 10:30pm
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: group.guests
    from: 'not_home'
    to: 'home'
  condition:
    - condition: time
      after: '18:30:00'
      before: '22:30:00'
    - condition: numeric_state
      entity_id: sensor.bedrooms_thermostat_hallway_temperature
      below: '75'
    - condition: template
      value_template: '{{ states.sensor.bedrooms_thermostat_hallway_operation_mode.state != "cool" }}'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.guest_floor_heat

# turn off at 11:30pm
- alias: NuHeat - Guest Turn off at 10:30pm
  initial_state: True
  hide_entity: False
  trigger:
    - platform: time
      at: '22:30:00'
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.guest_floor_heat






- alias: NuHeat - Eric, turn on at 11am if home
  initial_state: True
  hide_entity: False
  trigger:
    - platform: time
      at: '11:00:00'
  condition:
    - condition: state
      entity_id: device_tracker.ephone_2
      state: 'home'
    - condition: numeric_state
      entity_id: sensor.bedrooms_thermostat_hallway_temperature
      below: '76'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.guest_floor_heat

- alias: NuHeat - Eric, turn off at 2am
  initial_state: True
  hide_entity: False
  trigger:
    - platform: time
      at: '02:00:00'
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.guest_floor_heat

- alias: NuHeat - Eric, turn on when arrive home if 6:30pm < now < 2am
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: device_tracker.ephone_2
    from: 'not_home'
    to: 'home'
  condition:
    - condition: time
      after: '18:30:00'
      before: '02:00:00'
    - condition: numeric_state
      entity_id: sensor.bedrooms_thermostat_hallway_temperature
      below: '75'
    - condition: template
      value_template: '{{ states.sensor.bedrooms_thermostat_hallway_operation_mode.state != "cool" }}'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.guest_floor_heat


- alias: NuHeat - Master Input off
  initial_state: True
  trigger:
    platform: state
    entity_id: input_boolean.master_floor_heat
    from: 'off'
    to: 'on'
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.master_nuheat
      temperature: 90

- alias: NuHeat - Master Input on
  initial_state: True
  trigger:
    platform: state
    entity_id: input_boolean.master_floor_heat
    from: 'on'
    to: 'off'
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.master_nuheat
      temperature: 60

- alias: NuHeat - Guest Input off
  initial_state: True
  trigger:
    platform: state
    entity_id: input_boolean.guest_floor_heat
    from: 'off'
    to: 'on'
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.guest_nuheat
      temperature: 80

- alias: NuHeat - Guest Input on
  initial_state: True
  trigger:
    platform: state
    entity_id: input_boolean.guest_floor_heat
    from: 'on'
    to: 'off'
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.guest_nuheat
      temperature: 60


