- alias: People - Turn off guest/dog mode when we get back home
  initial_state: True
  trigger:
    platform: state
    entity_id: group.people
    from: 'not_home'
    to: 'home'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.occupants
        option: 'auto'

- alias: People - Set guests mode from notification
  initial_state: True
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SET_GUEST
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.occupants
        option: 'guests'

- alias: People - Set dog mode from notification
  initial_state: True
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SET_DOG
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.occupants
        option: 'dogs'

- alias: People - Notify on away
  initial_state: True
  trigger:
    platform: state
    entity_id: group.people
    from: 'home'
    to: 'not_home'
  condition:
    - condition: state
      entity_id: input_select.occupants
      state: 'auto'
  action:
    - service: notify.push_family
      data:
        message: "Setting to away mode"
        data:
          push:
            category: 'away'
            # badge: 1

- alias: People - Unlock whenever cam comes home
  initial_state: True
  trigger:
    - platform: state
      entity_id: person.cam
      from: 'not_home'
      to: 'home'
  action:
    - service: lock.unlock
      data:
        entity_id: lock.be469
    - service: notify.push_cam
      data:
        message: "Welcome home, cam"

- alias: People - Unlock whenever sandy comes home
  initial_state: True
  trigger:
    - platform: state
      entity_id: person.sandy
      from: 'not_home'
      to: 'home'
  action:
    - service: lock.unlock
      data:
        entity_id: lock.be469
    - service: notify.push_sandy
      data:
        message: "Welcome home, sandy"

- alias: People - Unlock whenever Tif comes back
  initial_state: True
  trigger:
    - platform: state
      entity_id: person.tif
      from: 'not_home'
      to: 'home'
  action:
    - service: lock.unlock
      data:
        entity_id: lock.be469

- alias: People - Notify when not home and door is opened
  initial_state: True
  trigger:
    - platform: state
      entity_id: lock.be469
      from: 'locked'
      to: 'unlocked'
  condition:
    - condition: state
      entity_id: group.people
      state: 'not_home'
  action:
    - service: notify.push_family
      data:
        message: "Door opened while not home"

