- alias: Water heater recirc off at 1am
  initial_state: True
  hide_entity: False
  trigger:
    platform: time
    at: '01:00:00'
  action:
    entity_id: switch.water_heater_recirc_pump
    service: switch.turn_off

- alias: Water heater recirc on at 5:45am
  initial_state: True
  hide_entity: False
  trigger:
    platform: time
    at: '05:45:00'
  condition:
    condition: state
    entity_id: group.people
    state: 'home'
  action:
    entity_id: switch.water_heater_recirc_pump
    service: switch.turn_on

- alias: Water heater recirc off when we leave
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: group.people
    from: 'home'
    to: 'not_home'
  action:
    entity_id: switch.water_heater_recirc_pump
    service: switch.turn_off

- alias: Water heater recirc on when we get home
  initial_state: True
  hide_entity: False
  trigger:
    # maybe use zone: https://community.home-assistant.io/t/notify-when-someone-is-home-or-not-home/347/11
    platform: state
    # using a group https://community.home-assistant.io/t/lights-on-when-home/16158
    entity_id: group.people
    from: 'not_home'
    to: 'home'
  action:
    entity_id: switch.water_heater_recirc_pump
    service: switch.turn_on
