- alias: Water heater - Recirc off at 1am
  id: water_heater_recirc_off_at_night
  initial_state: True
  trigger:
    platform: time
    at: "01:00:00"
  action:
    entity_id: switch.water_heater_recirc_pump
    service: switch.turn_off

- alias: Water heater - Recirc on at 5:45am
  id: water_heater_recirc_on_in_morning
  initial_state: True
  trigger:
    platform: time
    at: "05:45:00"
  condition:
    condition: state
    entity_id: group.people
    state: "home"
  action:
    entity_id: switch.water_heater_recirc_pump
    service: switch.turn_on

- alias: Water heater - Recirc on at 6pm
  id: water_heater_recirc_on_in_evening
  initial_state: True
  trigger:
    platform: time
    at: "18:00:00"
  condition:
    condition: state
    entity_id: group.people
    state: "home"
  action:
    entity_id: switch.water_heater_recirc_pump
    service: switch.turn_on

- alias: Water heater - Recirc off when we leave
  id: water_heater_recirc_off_when_we_leave
  initial_state: True
  trigger:
    platform: state
    entity_id: group.people
    from: "home"
    to: "not_home"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.occupants
        state: "auto"
      - condition: state
        entity_id: input_select.occupants
        state: "dogs"
  action:
    entity_id: switch.water_heater_recirc_pump
    service: switch.turn_off

- alias: Water heater - Recirc on when we get home
  id: water_heater_recirc_when_we_get_home
  initial_state: True
  trigger:
    # maybe use zone: https://community.home-assistant.io/t/notify-when-someone-is-home-or-not-home/347/11
    # using a group https://community.home-assistant.io/t/lights-on-when-home/16158
    - platform: state
      entity_id: group.people
      from: "not_home"
      to: "home"
    - platform: state
      entity_id: input_select.occupants
      from: "auto"
      to: "guests"
  action:
    entity_id: switch.water_heater_recirc_pump
    service: switch.turn_on
